HumanCapitalManagement.Web/Models/Projects/AllProjectsViewModel.cs
using HumanCapitalManagement.Contracts.Results.Projects;

namespace HumanCapitalManagement.Web.Models.Projects
{
    public class AllProjectsViewModel
    {
        public AllProjectsViewModel(List<ProjectsResultItem> projects)
        {
            Projects = projects;
        }

        public List<ProjectsResultItem> Projects { get; }
    }
}

HumanCapitalManagement.Web/Models/Projects/CreateProjectInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace HumanCapitalManagement.Web.Models.Projects
{
    public class CreateProjectInputModel
    {
        [Required(ErrorMessage = "Name is required.", AllowEmptyStrings = false)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Description is required.", AllowEmptyStrings = false)]
        public string Description { get; set; }

        [Required(ErrorMessage = "Size is required.")]
        [Range(0, int.MaxValue, ErrorMessage = "Size must be a positive number.")]
        public int Size { get; set; }
    }
}

HumanCapitalManagement.Web/Controllers/EmployeesController.cs
using HumanCapitalManagement.Contracts;
using HumanCapitalManagement.Contracts.Commands.Employees;
using HumanCapitalManagement.Contracts.Queries.Employees;
using HumanCapitalManagement.Contracts.Results.Employees;
using HumanCapitalManagement.Web.Models.Employees;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HumanCapitalManagement.Web.Controllers
{
    [Authorize(Roles = "ProjectManager")]
    public class EmployeesController : Controller
    {
        private readonly IAsyncQueryHandler<EmployeesByProjectIdQuery, EmployeesByProjectIdResult> employeesByProjectHandler;
        private readonly IAsyncCommandHandler<AddEmployeeCommand, AddEmployeeResult> addEmployeeHandler;
        private readonly IAsyncQueryHandler<EmployeeByIdQuery, EmployeeByIdResult> employeeByIdHandler;
        private readonly IAsyncCommandHandler<EditEmployeeCommand, EditEmployeeResult> editEmployeeHandler;
        private readonly IAsyncCommandHandler<DeleteEmployeeCommand, DeleteEmployeeResult> deleteEmployeeHandler;

        public EmployeesController(
            IAsyncQueryHandler<EmployeesByProjectIdQuery, EmployeesByProjectIdResult> employeesByProjectHandler,
            IAsyncCommandHandler<AddEmployeeCommand, AddEmployeeResult> addEmployeeHandler,
            IAsyncQueryHandler<EmployeeByIdQuery, EmployeeByIdResult> employeeByIdHandler,
            IAsyncCommandHandler<EditEmployeeCommand, EditEmployeeResult> editEmployeeHandler,
            IAsyncCommandHandler<DeleteEmployeeCommand, DeleteEmployeeResult> deleteEmployeeHandler)
        {
            this.employeesByProjectHandler = employeesByProjectHandler;
            this.addEmployeeHandler = addEmployeeHandler;
            this.employeeByIdHandler = employeeByIdHandler;
            this.editEmployeeHandler = editEmployeeHandler;
            this.deleteEmployeeHandler = deleteEmployeeHandler;
        }

        [HttpGet]
        public async Task<IActionResult> All(string projectId)
        {
            var employeesQuery = new EmployeesByProjectIdQuery(projectId);
            var employeesResult = await this.employeesByProjectHandler.HandleAsync(employeesQuery);

            var viewModel = new AllEmployeesViewModel(employeesResult.Employees, projectId);
            return View("AllEmployees", viewModel);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return PartialView("_AddEmployee");
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddEmployeeInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                var errorMessage = ModelState.Values
                    .SelectMany(x => x.Errors)
                    .Select(x => x.ErrorMessage)
                    .FirstOrDefault();

                return Json(new { ErrorMessage = errorMessage, Succeed = false });
            }

            var addEmployeeCommand = new AddEmployeeCommand(inputModel.FirstName, inputModel.LastName, inputModel.Salary, inputModel.Position, inputModel.ProjectId);
            var addEmployeeResult = await this.addEmployeeHandler.HandleAsync(addEmployeeCommand);

            return Json(new { addEmployeeResult.Succeed, addEmployeeResult.ErrorMessage });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var employeeByIdQuery = new EmployeeByIdQuery(id);
            var employeeByIdResult = await this.employeeByIdHandler.HandleAsync(employeeByIdQuery);

            var employee = employeeByIdResult.Employee;

            var editEmployeeModel = new EditEmployeeModel()
            {
                Id = id,
                FirstName = employee.FirstName,
                LastName = employee.LastName,
                Salary = employee.Salary,
                Position = employee.Position,
            };

            return PartialView("_EditEmployee", editEmployeeModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditEmployeeModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                var errorMessage = ModelState.Values
                    .SelectMany(x => x.Errors)
                    .Select(x => x.ErrorMessage)
                    .FirstOrDefault();

                return Json(new { ErrorMessage = errorMessage, Succeed = false });
            }

            var editEmployeeCommand = new EditEmployeeCommand(inputModel.Id, inputModel.FirstName, inputModel.LastName, inputModel.Position, inputModel.Salary);
            var editEmployeeResult = await this.editEmployeeHandler.HandleAsync(editEmployeeCommand);

            return Json(new { editEmployeeResult.Succeed, editEmployeeResult.ErrorMessage });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var deleteEmployeeCommand = new DeleteEmployeeCommand(id);
            var deleteEmployeeResult = await this.deleteEmployeeHandler.HandleAsync(deleteEmployeeCommand);

            return Json(new { deleteEmployeeResult.Succeed, deleteEmployeeResult.ErrorMessage });
        }
    }
}

HumanCapitalManagement.Web/Controllers/ProjectsController.cs
using HumanCapitalManagement.Contracts.Queries.Projects;
using HumanCapitalManagement.Contracts.Results.Projects;
using HumanCapitalManagement.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using HumanCapitalManagement.Web.Models.Projects;
using HumanCapitalManagement.Contracts.Commands.Projects;

namespace HumanCapitalManagement.Web.Controllers
{
    [Authorize(Roles = "ProjectManager")]
    public class ProjectsController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly IAsyncQueryHandler<ProjectsByUserIdQuery, ProjectsByUserIdResult> projectsHandler;
        private readonly IAsyncCommandHandler<CreateProjectCommand, CreateProjectResult> createProjectHandler;

        public ProjectsController(
            UserManager<IdentityUser> userManager,
            IAsyncQueryHandler<ProjectsByUserIdQuery, ProjectsByUserIdResult> projectsHandler,
            IAsyncCommandHandler<CreateProjectCommand, CreateProjectResult> createProjectHandler)
        {
            this.userManager = userManager;
            this.projectsHandler = projectsHandler;
            this.createProjectHandler = createProjectHandler;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var userId = this.userManager.GetUserId(User);
            var projectsQuery = new ProjectsByUserIdQuery(userId);
            var projectsResult = await this.projectsHandler.HandleAsync(projectsQuery);

            var viewModel = new AllProjectsViewModel(projectsResult.Projects);

            return View("AllProjects", viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("CreateProject");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProjectInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateProject", inputModel);
            }

            var userId = this.userManager.GetUserId(User);

            var createProjectCommand = new CreateProjectCommand(
                inputModel.Name, inputModel.Description, inputModel.Size, userId);
            var createProjectResult = await this.createProjectHandler.HandleAsync(createProjectCommand);

            if (!createProjectResult.Succeed)
            {
                ViewBag.ErrorMessage = createProjectResult.ErrorMessage;
                return View("CreateProject", inputModel);
            }

            return RedirectToAction(nameof(All));
        }
    }
}

HumanCapitalManagement.Web/Views/Projects/AllProjects.cshtml
@model HumanCapitalManagement.Web.Models.Projects.AllProjectsViewModel

<div class="mt-5">
    <h1 class="fw-semibold text-center mb-5">All Projects</h1>
    @if (!Model.Projects.Any())
    {
        <div class="d-flex align-items-center flex-column">
            <span class="fw-semibold">No projects have been created yet.</span>
            <a class="btn btn-dark fw-semibold mt-3" asp-controller="Projects" asp-action="Create">New Project</a>
        </div>
    }
    else
    {
        <table class="table border-dark table-bordered table-hover mt-3 text-center">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Size</th>
                    <th scope="col">Date of Creation</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var project in Model.Projects)
                {
                    <tr>
                        <td><a class="fw-semibold text-dark" asp-controller="Employees" asp-action="All" asp-route-projectid="@project.Id">@project.Name</a></td>
                        <td>@project.Description</td>
                        <td>@project.Size</td>
                        <td>@project.CreateDate</td>
                    </tr>
                }
            </tbody>
        </table>
        <a class="btn btn-dark fw-semibold float-end" asp-controller="Projects" asp-action="Create">New Project</a>
    }
</div>

HumanCapitalManagement.Web/Views/Projects/CreateProject.cshtml
@using HumanCapitalManagement.Web.ViewHelpers
@model HumanCapitalManagement.Web.Models.Projects.CreateProjectInputModel

<h1 class="fw-semibold mb-3 text-center mt-5">Create Project</h1>
<form class="mt-5 w-50 m-auto" asp-controller="Projects" asp-action="Create" method="post">
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="row mb-3">
            <span class="fw-semibold">@ViewBag.ErrorMessage</span>
        </div>
    }
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input asp-for="@Model.Name" type="text" class="form-control" />
        </div>
        <span asp-validation-for="@Model.Name" class="text-danger"></span>
    </div>
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-10">
            <textarea asp-for="@Model.Description" class="form-control"></textarea>
        </div>
        <span asp-validation-for="@Model.Description" class="text-danger"></span>
    </div>
    <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Size</label>
        <div class="col-sm-10">
            <input asp-for="@Model.Size" type="number" class="form-control" />
        </div>
        <span asp-validation-for="@Model.Size" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-dark mt-3 float-end fw-semibold">Create</button>
</form>