HumanCapitalManagement.Web/Controllers/AccountsController.cs
using HumanCapitalManagement.Contracts;
using HumanCapitalManagement.Contracts.Commands.Accounts;
using HumanCapitalManagement.Contracts.Results.Accounts;
using HumanCapitalManagement.Web.Models.Accounts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HumanCapitalManagement.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AccountsController : Controller
    {
        private readonly IAsyncCommandHandler<CreateAccountCommand, CreateAccountResult> createAccountHandler;

        public AccountsController(IAsyncCommandHandler<CreateAccountCommand, CreateAccountResult> createAccountHandler)
        {
            this.createAccountHandler = createAccountHandler;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("CreateAccount");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateAccountInputModel input)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateAccount", input);
            }

            var createAccountCommand = new CreateAccountCommand(input.Email, input.Password, input.Role);
            var createAccountResult = await this.createAccountHandler.HandleAsync(createAccountCommand);

            ViewData["Message"] = createAccountResult.Message;
            ViewData["Succeed"] = createAccountResult.Succeed;

            return View("CreateAccount", input);
        }
    }
}

HumanCapitalManagement.Web/Controllers/ProjectsController.cs
using HumanCapitalManagement.Contracts.Queries.Projects;
using HumanCapitalManagement.Contracts.Results.Projects;
using HumanCapitalManagement.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using HumanCapitalManagement.Web.Models.Projects;
using HumanCapitalManagement.Contracts.Commands.Projects;

namespace HumanCapitalManagement.Web.Controllers
{
    [Authorize(Roles = "ProjectManager")]
    public class ProjectsController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly IAsyncQueryHandler<ProjectsByUserIdQuery, ProjectsByUserIdResult> projectsHandler;
        private readonly IAsyncCommandHandler<CreateProjectCommand, CreateProjectResult> createProjectHandler;

        public ProjectsController(
            UserManager<IdentityUser> userManager,
            IAsyncQueryHandler<ProjectsByUserIdQuery, ProjectsByUserIdResult> projectsHandler,
            IAsyncCommandHandler<CreateProjectCommand, CreateProjectResult> createProjectHandler)
        {
            this.userManager = userManager;
            this.projectsHandler = projectsHandler;
            this.createProjectHandler = createProjectHandler;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var userId = this.userManager.GetUserId(User);
            var projectsQuery = new ProjectsByUserIdQuery(userId);
            var projectsResult = await this.projectsHandler.HandleAsync(projectsQuery);

            var viewModel = new AllProjectsViewModel(projectsResult.Projects);

            return View("AllProjects", viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("CreateProject");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProjectInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateProject", inputModel);
            }

            var userId = this.userManager.GetUserId(User);

            var createProjectCommand = new CreateProjectCommand(
                inputModel.Name, inputModel.Description, inputModel.Size, userId);
            var createProjectResult = await this.createProjectHandler.HandleAsync(createProjectCommand);

            if (!createProjectResult.Succeed)
            {
                ViewBag.ErrorMessage = createProjectResult.ErrorMessage;
                return View("CreateProject", inputModel);
            }

            return RedirectToAction(nameof(All));
        }
    }
}

HumanCapitalManagement.Web/Views/Shared/_Layout.cshtml
@using HumanCapitalManagement.Data.Enums
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HumanCapitalManagement</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HumanCapitalManagement.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <div>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    @if (User.IsInRole(UserRole.Admin.ToString()))
                    {
                        <a class="navbar-brand" asp-controller="Accounts" asp-action="Create">Create Account</a>
                    }
                    @if (User.IsInRole(UserRole.ProjectManager.ToString()))
                    {
                        <a class="navbar-brand" asp-controller="Projects" asp-action="All">Projects</a>
                    }
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>